### PR TITLE
**NO-MERGE** Use Search instead of hand-rolled pipeline

### PR DESCRIPTION
**Pull request by heaths**
This is for a demo and should not be merged as-is.

### CODE REVIEW

**Comment by jongio** [comment]
As you mentioned, I won't plan on merging this.  I can see how we could update the demo to add an alternate version that uses search as a service under /net/services/.

**Comment by heaths** [comment]
We can discuss it more and I could probably find some time soon to make changes to support that (for Python, too...though: azure/azure-sdk-for-python#12455. I can work around by using the raw `SearchField`). For now, this was just to get enough working for a demo.

**Comment by heaths** [comment]
FWIW, had I not had to check in the code to create the index, indexer, data source connection, and skillset - most of that can be done manually online, but 1) is not part of an ARM template, alas, and 2) the current online editor for skillsets is not as robust unless you already have something to modify in a "debug session" - this draft PR would be almost entirely deleted code.

**Comment by heaths** [comment]
Demo is finished

**Pull request closed without merging**
